// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServidorConsola.DAL;

#nullable disable

namespace ServidorConsola.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221012183103_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ServidorConsola.entidades.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ServidorConsola.entidades.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dsiponibilidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MesaId");

                    b.ToTable("Mesa");

                    b.HasData(
                        new
                        {
                            MesaId = 1,
                            Capacidad = 4,
                            Dsiponibilidad = true,
                            Forma = "Redonda",
                            Precio = 1500.0,
                            Ubicacion = "frente a la playa"
                        },
                        new
                        {
                            MesaId = 2,
                            Capacidad = 4,
                            Dsiponibilidad = true,
                            Forma = "Cuadrado",
                            Precio = 1500.0,
                            Ubicacion = "frente a la playa"
                        });
                });

            modelBuilder.Entity("ServidorConsola.entidades.Reservacion", b =>
                {
                    b.Property<int>("reservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("reservacionId");

                    b.ToTable("Reservacion");
                });
#pragma warning restore 612, 618
        }
    }
}
